/* Dyanmic Or Runtime Memory Allocation */

#include<stdio.h>
#include<stdlib.h>

void main()
{
	int *no;

	// "no" is a pointer variable and memory address generated by malloc function will be assigned to the pointer variable	
	// "int*" used to cast "void" memory space to type integer
	
	no = (int*)malloc(sizeof(int));
	printf("\n memory address = %u",no);
	
}

